//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeRecord.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpWorkHour
    {
        public int EmpHoursID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public double Hours { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
